CREATE DATABASE stud;
USE stud;

CREATE TABLE students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    addr VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    pin VARCHAR(255) NOT NULL
);

CREATE TABLE studentsmarks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CGPI FLOAT NOT NULL
);
